solidusio/edgeguides

getting-started/what-is-solidus.md

Using `--skip-webpack-install` is only preventing the Rails install generator from 
running `webacker:install`, but the `webpacker` gem is still added to the Gemfile.
Ref: https://github.com/rails/rails/issues/35484
In the context of a fresh app that uses the bare minimum set of tools to run Solidus
we don't need that. People can still add it later if needed.

Install solidus without javascript compilers (webpacker)

---

getting-started/what-is-solidus.md

This PR updates the instructions for installing Solidus from version 2.10 (and under) to 2.11.

Update install instructions to Solidus 2.11

---

getting-started/deployment.md
getting-started/extensions.md
getting-started/what-is-solidus.md

This commit fixes some minor grammatical typos and tries to improve readability. Some longer sentences have been split into multiple sentences to make them easier to scan and parse.

Minor typo and clarity fixes

---

docs/advanced-solidus/custom-authentication.mdx
docs/getting-started/installing-solidus.mdx
docs/getting-started/upgrading-solidus.mdx

PayPal is no longer an option in the installation script. See solidusio/solidus#4494.
Solidus Starter Frontend is now considered stable and it's installable from the main installation script. See solidusio/solidus#4490

Update installation guide and references to solidus_starter_frontend

---

docs/customization/customizing-emails.mdx

This change rewrites the original guide page into the new guide.
See https://github.com/solidusio/legacy-guides/blob/0c32c2a06129c62575c7c2a7e4631abde1873ec8/source/developers/customizations/customizing-mailers.html.md

Add Customizing Transactional Emails page

---

docusaurus.config.js

This service is free for open source projects, thanks!
Some notes:
1. I enabled contextual search, this should allow us to have the search working when we'll have multiple versions of the guide published, let's revist when that happens.
2. For reference, I follewed this guide: https://docusaurus.io/docs/search and on that page, there's a section that describe how to style the search component. Might be useful in a while.
Please also note that I left keys and appID public. They are supposed to be public because they will be rendered in the final HTML, so no need of an ENV variable for them.

Add searchbar powered by Algolia Docsearch

---

docusaurus.config.js

This PR:
- Adds an "Edit this page" link on each page. It links to GitHub so it's always clear what to do to contribute
- Adds an announcement bar with an initial message to get some more stars on the GH repository. We can configure it later for example to request feedback via survey or similar things cc @aldesantis 
- Removes the versioning configuration. We will re-enable it when we are satisfied with the content, and we can create multiple versions. Doing it now will force us to manually copy/paste changes from version to version. Here's the versioning guide, for future reference: https://docusaurus.io/docs/next/versioning.

Several UX improvements

---

docs/advanced-solidus/returns.mdx
docs/advanced-solidus/state-machines.mdx
docs/advanced-solidus/stock-and-fulfillment.mdx
docs/advanced-solidus/tax-calculation.mdx
docs/how-tos/_category_.json
docs/how-tos/how_to_customize_return_eligibility_rules_skipping_rmas.mdx
docs/how-tos/how_to_modify_valid_exchange_items_in_returns.mdx
docs/how-tos/how_to_use_custom_logic_to_calculate_return_refunds.mdx

This PR adds documentation about the returns system in Solidus, plus a couple of related how-to guides:
- How to skip RMAs in returns
- How to modify valid exchanges in returns
Please tell me if you think another how-to guide is essential. There are just too many things to cover in this initial spike :slightly_smiling_face: 
I'm also using it as a POC for adopting the [Diátaxis](https://diataxis.fr) framework (ref. #60):
- My idea is to have high-level explanations for different Solidus sub-systems or concepts.
- Related how-to guides are listed on the explanation page.
- Nonetheless, how-to guides are hierarchically at the same level as explanations. That's because a single how-to guide can apply to different sub-systems/concepts, and users can find them more quickly this way.
- …

Add guides for returns and a couple of related how-to guides

---

docs/advanced-solidus/state-machines.mdx
docs/how-tos/how-to-add-orthogonal-behavior-to-state-machines-publishing-events.mdx
docs/how-tos/how-to-customize-existing-state-machines.mdx
docs/how-tos/how-to-customize-return-eligibility-rules-skipping-rmas.mdx
docs/how-tos/how-to-modify-valid-exchange-items-in-returns.mdx
docs/how-tos/how-to-replace-an-existing-state-machine.mdx
docs/how-tos/how-to-use-custom-logic-to-calculate-return-refunds.mdx

Basically, we're separating explanation from how-to guides. We're realizing
that the re-organization makes some of the text boxes unnecessary (probably a
smell that they were out of context).
There's also a preliminary commit that fixes previous small issues.

Adapt state machine guides to Diátaxis

---

docs/getting-started/installing-solidus.mdx

Our install instructions didn't account for libvips, which was introduced on
Rails 6 and it's defailt on Rails 7.

Update install instructions to account for libvips

---

src/theme/NotFound.js

This will help people with broken links.
The `NotFound` component has been swizzled following the [documentation](https://docusaurus.io/docs/swizzling#swizzling-theme-components):
```
npm run swizzle @docusaurus/theme-classic NotFound
```
- ~[ ] I have followed the [Diátaxis](https://diataxis.fr/) framework in my PR.~

Add a link to the legacy guide in the 404 page

---

src/css/custom.css

We noticed an issue on the search when the dark mode is enabled:
Changing the color of the CSS var `--ifm-color-primary` to the blue of Solidus, fixes the issue and improves the readability of links and active elements.
Update
The blue has been slightly changed, in order to pass all the accessibility tests.
Source: https://webaim.org/resources/contrastchecker/

Fix primary color for dark theme mode

---

docs/customization/subscribing-to-events.mdx

This PR is sponsored by [MagmaLabs](https://www.magmalabs.io/)
- Update list events to `bus.registry.event_names` https://github.com/nebulab/omnes/blame/main/README.md#L496
- Update bus helpers use https://github.com/solidusio/solidus/blob/master/core/lib/spree/testing_support/bus_helpers.rb#L69

update events guide

---

docs/advanced-solidus/promotions-system.mdx

To avoid resolving Spree as AmazingStore::Spree instead of ::Spree.

Add missing :: operators for constants lookup

---

docs/getting-started/installing-solidus.mdx
versioned_docs/version-3.2/getting-started/installing-solidus.mdx

After a recent update, now Bolt has been added as an installable payment method during Solidus installation.
The doc has been updated to reflect the same information.

Update documentation for the Bolt Payment Method

---

README.md
bin/backport

Docusarus default [versioning strategy](https://docusaurus.io/docs/versioning) keeps everything on the same branch. Having to copy changes manually to older branches is a pain.
We ship a helper `bin/backport` script that will automate the process when given a git reference that only contains changes to the edge version.
```
Usage: bin/backport [-r ref] [-n number_of_commits] -v version [-v version ...]
-r ref: the ref to backport from (default: HEAD)
-n number_of_commits: the number of commits to backport (default: 1)
-v versions: the versions to backport to (default: none)
```

Helper command to backport documentation

---

docs/advanced-solidus/images-and-image-processing.mdx
versioned_docs/version-3.2/advanced-solidus/images-and-image-processing.mdx
versioned_docs/version-3.3/advanced-solidus/images-and-image-processing.mdx

We found that the documentation on customizing image sizes for products and
variants was outdated and suggested users introduce a decorator. This was
[fixed previously](https://github.com/solidusio/solidus/pull/4245) in the Legacy guides and we have ported the updated documentation
to the new version here.
Fixes #94

Update image size customization docs

---

.dockerdev/Dockerfile
docker-compose.yml

The Node image for Docker [recommends](https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#non-root-user) using `node` as the default user.
Using another one worked with no problems in the past. For some reason, it's now not respecting the `USER` directive on the Dockerfile and using the `node` user regardless. We'll use the default recommendation to avoid troubles.
- ~[ ] I have followed the [Diátaxis](https://diataxis.fr/) framework in my PR.~

Use recommended user for the Docker Node image

---

docs/upgrading-solidus/v3.3.mdx
versioned_docs/version-3.3/upgrading-solidus/v3.3.mdx
versioned_docs/version-3.4/upgrading-solidus/v3.3.mdx

We started adding that information on v3.4 (see #100).

Add minimal requirements to v3.3 upgrade guides

---

docs/getting-started/upgrading-solidus.mdx

That's what we have done in https://github.com/solidusio/solidus/pull/5012 for technical reasons.
We're also using "approach" instead of "policy" to avoid confusion with our [official policy](https://solidus.io/release_policy/), which doesn't mention this kind of support yet.

Inform we can drop support for maintained Ruby/Rails versions in a major

---

docs/cookbook/redefining-checkout-steps.mdx
versioned_docs/version-3.2/cookbook/redefining-checkout-steps.mdx
versioned_docs/version-3.3/cookbook/redefining-checkout-steps.mdx
versioned_docs/version-3.4/cookbook/redefining-checkout-steps.mdx

in favor of the new overrides convention.

Remove old references to decorators

---

docs/cookbook/redefining-checkout-steps.mdx

[redefining-checkout-steps.mdx](https://github.com/solidusio/edgeguides/commit/98934d92675f9e39504065faa33f9bb34f370c22) was missing a backtick `` ` ``, this pr adds it so that the code block in section **Conditional checkout steps** renders correctly.

Fix markdown typo

---

versioned_docs/version-3.4/upgrading-solidus/v3.3.mdx

Fixed a typo on `ransack` legacy attribute names.

Fix ransack attribute names

---

docusaurus.config.js
policies/community-guidelines.mdx
policies/release_policy.mdx
policies/security.mdx
src/theme/SupportedVersions.js

It is almost a 1-1 copy from the solidus website repository, but I had to rewrite in JS the code that creates the supported versions table and check dynamically if a version is still supported or not (thanks for the help ChatGPT 🤖).
~When approved, I'll generate the corresponding pages for the 4.1 version for immediate availability.~ see https://github.com/solidusio/edgeguides/pull/120#issuecomment-1625543089

Move policies pages from solidus.io to guides

---

docs/upgrading-solidus/v3.3.mdx
docs/upgrading-solidus/v3.4.mdx
docs/upgrading-solidus/v4.0.mdx
docs/upgrading-solidus/v4.1.mdx
src/theme/PRLink.js
versioned_docs/version-3.3/upgrading-solidus/v3.3.mdx
versioned_docs/version-3.4/upgrading-solidus/v3.3.mdx
versioned_docs/version-3.4/upgrading-solidus/v3.4.mdx
versioned_docs/version-4.0/upgrading-solidus/v3.3.mdx
versioned_docs/version-4.0/upgrading-solidus/v3.4.mdx
versioned_docs/version-4.0/upgrading-solidus/v4.0.mdx
versioned_docs/version-4.1/upgrading-solidus/v3.3.mdx
versioned_docs/version-4.1/upgrading-solidus/v3.4.mdx
versioned_docs/version-4.1/upgrading-solidus/v4.0.mdx
versioned_docs/version-4.1/upgrading-solidus/v4.1.mdx

This makes it work with non-docusaurus enabled preview systems and MD renderers.

Make the PRLink use the tag contents as the title

---

docusaurus.config.js

1. **Customization Guide Redirect**
- **From**: `/developers/customizations/overview`
- **To**: `/customization/customizing-your-storefront`
2. **Installation Guide Redirect**
- **From**: `/developers/getting-started/first-time-installation`
- **To**: `/getting-started/installing-solidus`
ℹ️ More details here: https://github.com/solidusio/solidus/pull/5404#discussion_r1342903497
1. **Customization Guide Redirect**
- https://rainerd-fix-redirects.edgeguides.pages.dev/developers/customizations/overview
2. **Installation Guide Redirect**
- https://rainerd-fix-redirects.edgeguides.pages.dev/developers/getting-started/first-time-installation

Fix missing redirects in documentation URLs

---

docs/advanced-solidus/promotions-system.mdx
docs/getting-started/installing-solidus.mdx
docs/how-tos/how-to-use-a-custom-promotion-adjuster.mdx
docs/upgrading-solidus/v4.4.mdx

Starts 4.4 upgrade notes and adds `solidus_promotions` introduction.

Start Solidus 4.4 upgrade notes

---

docs/how-tos/how-to-use-a-custom-brand-selector.mdx

This PR updates the documentation to guide developers on how to customize the brand selection logic in Solidus. It explains how to configure a custom brand selector class, allowing businesses to define brand logic that suits their needs. 
The update helps developers understand how to easily adjust the default behavior without altering core code, giving them more flexibility while keeping everything clear and simple.

Introducing product brand guidelines

---

docs/customization/customizing-the-backend.mdx
versioned_docs/version-4.3/customization/customizing-the-backend.mdx
versioned_docs/version-4.4/customization/customizing-the-backend.mdx

Added clarification regarding the parallel admin engine situation to help new developers with onboarding.

Mention dual-admin transitory period in the backend customisation guide

---

AdditionalLicenses.md

The source code of docusaurus was not covered by a License. This file closes the gap.
The current repository had License gaps as docusaurus requires MIT License to provided with copyright of the original Author.

Create License for Docusaurus Source Code

---

docs/customization/subscribing-to-events.mdx

Built-in Solidus event subscribers are now configurable since solidusio/solidus#6234 was merged. The docs added by this pull request help users understand how to add or remove built-in event subscribers in their applications.

Add docs for configurable event subscribers
