SUMMARY.md, advanced-solidus/checkout-steps.md
I couldn't really figure out how to run gitbook locally, so I hope this looks good. 😬
=> Add checkout steps guide

advanced-solidus/custom-authentication.md, advanced-solidus/extension-development.md, customization/customizing-the-api.md, customization/customizing-the-backend.md, customization/customizing-the-core.md, getting-started/testing-solidus.md, getting-started/upgrading-solidus.md
Small typos found while reading during the onboarding. Feel free to better rephrase my fixes if needed.
Kudos to everyone involved for such a great guide! 🎉
=> Fix typos and rephrase for better legibility

customization/customizing-the-core.md
Minor change to https://edgeguides.solidus.io/customization/customizing-the-core#using-overrides to make the code snippet more logical (and in line with the code)
=> Update `#available?` code snippet in customizing-the-core.md

package.json, yarn.lock
We were on a release candidate already, so it is not much of a change.
=> Upgrade Docusaurus to v2

.github/pull_request_template.md, README.md, docs/advanced-solidus/custom-authentication.mdx, docs/advanced-solidus/extension-development.mdx, docs/advanced-solidus/images-and-image-processing.mdx, docs/advanced-solidus/model-preferences.mdx, docs/advanced-solidus/payments-and-refunds.mdx, docs/advanced-solidus/permission-management.mdx, docs/advanced-solidus/promotions-system.mdx, docs/advanced-solidus/state-machines.mdx, docs/advanced-solidus/stock-and-fulfillment.mdx, docs/advanced-solidus/tax-calculation.mdx, docs/cookbook/redefining-checkout-steps.mdx, docs/cookbook/using-the-graphql-api.mdx, docs/customization/customizing-emails.mdx, docs/customization/customizing-the-api.mdx, docs/customization/customizing-the-backend.mdx, docs/customization/customizing-the-core.mdx, docs/customization/customizing-your-storefront.mdx, docs/customization/subscribing-to-events.mdx, docs/getting-started/deploying-your-store.mdx, docs/getting-started/installing-solidus.mdx, docs/getting-started/testing-solidus.mdx, docs/getting-started/upgrading-solidus.mdx, docs/getting-started/using-extensions.mdx
We closed #60 becuase that work should be done iteratively. 
This PR contains a set of changes that will help us and contributors stay alined to the framework. 
Please note that on 68213e79a49190985c5fdd738121386ea035378a, I blindly applied the `needs-diataxis-rewrite: true` metatag to all the pages. When in the process of rewriting them individually, we will consider if it is valid or not.
=> Several improvements to enforce Diátaxis adoption

docs/customization/customizing-the-backend.mdx
I noticed this while reading this 😄 
I have not done this things 🙈
=> Fix typo in file path

docs/getting-started/installing-solidus.mdx, versioned_docs/version-3.2/getting-started/installing-solidus.mdx
=> Fix outdated line about being prompted for admin creds

docs/advanced-solidus/model-preferences.mdx
Update the documentation for solidusio/solidus#4858.
=> Update the documentation for solidusio/solidus#4858

README.md, docs/advanced-solidus/state-machines.mdx, docs/customization/customizing-the-core.mdx
- Added missing "O" in "or"
- Removed "for" in "look for through ..."
- Updated Line number to where the OrderMerger class config option is on app_configuration
=> Update grammar in advanced-solidus/state-machines

docs/advanced-solidus/promotions-system.mdx, docs/how-tos/how-to-use-a-custom-promotion-adjuster.mdx, docs/upgrading-solidus/v3.3.mdx, versioned_docs/version-3.3/advanced-solidus/promotions-system.mdx, versioned_docs/version-3.3/how-tos/how-to-use-a-custom-promotion-adjuster.mdx, versioned_docs/version-3.3/upgrading-solidus/v3.3.mdx
Both in next and v3.3. This PR also updates the upgrade guide for v3.3 so that it links to the new page.
=> Add an how-to for the new promotion adjuster class

docs/advanced-solidus/tax-calculation.mdx, docs/how-tos/how-to-setup-colorado-delivery-fee.mdx, docs/upgrading-solidus/v3.3.mdx, versioned_docs/version-3.3/advanced-solidus/tax-calculation.mdx, versioned_docs/version-3.3/how-tos/how-to-setup-colorado-delivery-fee.mdx, versioned_docs/version-3.3/upgrading-solidus/v3.3.mdx
=> Add Colorado Delivery Fee Setup how to

docs/advanced-solidus/custom-authentication.mdx, docs/customization/customizing-the-api.mdx, docs/how-tos/how-to-sign-in-to-the-solidus-api-using-solidus_auth_devise.mdx, versioned_docs/version-3.2/advanced-solidus/custom-authentication.mdx, versioned_docs/version-3.2/customization/customizing-the-api.mdx, versioned_docs/version-3.2/how-tos/how-to-sign-in-to-the-solidus-api-using-solidus_auth_devise.mdx, versioned_docs/version-3.3/advanced-solidus/custom-authentication.mdx, versioned_docs/version-3.3/customization/customizing-the-api.mdx, versioned_docs/version-3.3/how-tos/how-to-sign-in-to-the-solidus-api-using-solidus_auth_devise.mdx
References https://github.com/solidusio/solidus/issues/4871
I'm for now only providing the version for the edge version of Solidus. I'll copy it to the other versions once we agree on the content.
=> How to sign in to the API via solidus_auth_devise

docs/how-tos/how-to-use-searchkick-for-search-autocomplete.mdx
=> Add how-to to use Searchkick for search autocomplete

versioned_docs/version-3.3/advanced-solidus/permission-management.mdx
Fixing a typo in the command. It doesn't work as previously written.
=> Correct db:seed command

docs/upgrading-solidus/v3.4.mdx, versioned_docs/version-3.4/upgrading-solidus/v3.4.mdx
=> Fix the check in the v3.4 upgrade guide

docs/getting-started/upgrading-solidus.mdx, versioned_docs/version-3.2/getting-started/upgrading-solidus.mdx, versioned_docs/version-3.3/getting-started/upgrading-solidus.mdx, versioned_docs/version-3.4/getting-started/upgrading-solidus.mdx
=> Add info on how to assimilate DB updates

versioned_docs/version-3.2/getting-started/upgrading-solidus.mdx, versioned_docs/version-3.3/getting-started/upgrading-solidus.mdx, versioned_docs/version-3.4/getting-started/upgrading-solidus.mdx
=> Backport Rails support approach changes to older docs

docs/upgrading-solidus/v4.0.mdx
=> Fix release date for Solidus v4

docs/getting-started/upgrading-solidus.mdx, versioned_docs/version-3.2/getting-started/upgrading-solidus.mdx, versioned_docs/version-3.3/getting-started/upgrading-solidus.mdx, versioned_docs/version-3.4/getting-started/upgrading-solidus.mdx
The CHANGELOG link points to a nonexistent resource.
=> Fix incorrect link

docs/upgrading-solidus/v3.3.mdx, versioned_docs/version-3.2/cookbook/redefining-checkout-steps.mdx, versioned_docs/version-3.3/cookbook/redefining-checkout-steps.mdx, versioned_docs/version-3.3/upgrading-solidus/v3.3.mdx, versioned_docs/version-3.4/cookbook/redefining-checkout-steps.mdx, versioned_docs/version-4.0/cookbook/redefining-checkout-steps.mdx, versioned_docs/version-4.0/upgrading-solidus/v3.3.mdx
This PR ports fixes merged on https://github.com/solidusio/edgeguides/pull/112 & https://github.com/solidusio/edgeguides/pull/108 to latest and versioned docs where applicable.
=> Port latest fixes

CONTRIBUTING.md
Contains instructions on how to contribute asking people to prefer using Diátaxis if possible. It also includes a paragraph to document the process of Diátaxis migrations for existing pages.
=> Add a CONTRIBUTION.md file with instructions

docs/upgrading-solidus/v3.3.mdx, docs/upgrading-solidus/v3.4.mdx, docs/upgrading-solidus/v4.0.mdx, docs/upgrading-solidus/v4.1.mdx, package.json, yarn.lock
Target merge date: ~Tuesday, 27/06/23~ Thursday 30/06/23
Adds Upgrade Guides for v4.1
=> v4.1 upgrade guide

docs/getting-started/installing-solidus.mdx, docs/getting-started/testing-solidus.mdx, versioned_docs/version-4.1/getting-started/installing-solidus.mdx, versioned_docs/version-4.1/getting-started/testing-solidus.mdx
Please go commit by commit for more information. They have been backported to v4.1 for immediate availability.
=> Improve Getting Started Section

docs/customization/customizing-the-backend.mdx, versioned_docs/version-3.2/customization/customizing-the-backend.mdx, versioned_docs/version-3.3/customization/customizing-the-backend.mdx, versioned_docs/version-3.4/customization/customizing-the-backend.mdx, versioned_docs/version-4.0/customization/customizing-the-backend.mdx, versioned_docs/version-4.1/customization/customizing-the-backend.mdx
=> Remove text that was pasted by mistake

yarn.lock
=> Update caniuse info

docs/customization/customizing-the-backend.mdx, versioned_docs/version-4.2/customization/customizing-the-backend.mdx
Updates 4.2 menu_item examples to match changes made here: https://github.com/solidusio/solidus/commit/c9e151ce276875d17e1013c61d272734f7b8ce90#diff-b9a08bd588c0052ee198e4df7b36adc56c099e2d77ee2bb100568ede58f32744R54-R63 
- Made a simple change, the pages that were edited are still pending `needs-diataxis-rewrite`
=> update new menu_item config examples

policies/security.mdx, src/theme/SupportedVersions.js
This makes it easier to know what to do in case we land on the 30th of February.
=> Switch from 18 natural months to exactly 540 (18*30) days after

docs/advanced-solidus/promotions-system.mdx, docs/how-tos/how-to-use-a-custom-promotion-adjuster.mdx, docs/upgrading-solidus/v4.4.mdx
This adds information about the new promotion system to the v4.4 release notes, and updates some configuration endpoints in the existing documentation for the legacy promotion system.
=> Solidus promotions blurb

docs/upgrading-solidus/v4.4.mdx
=> Finalize 4.4 Release notes

src/theme/SupportedVersions.js
=> Update SupportedVersions.js with 4.4

CONTRIBUTING.md
There were no guidelines to align contributions that deface / overwrite starter-frontend behavior.
=> Updated contribution guidelines with some information about starter-frontend impacting changes

docs/upgrading-solidus/v4.5.mdx
Adds notes about  developer experience improvements
=> Add notes about flickwerk to 4.5 release notes

License.md
Implements the standard solidus license.
=> Solidus License
